[global]
plan = "random_walk_test"
case = "random_walk_test"
builder = "docker:go"
runner = "local:docker"

[[groups]]
id = "default"
instances.count = 20

    [groups.run]
    [groups.run.test_params]
    want_forwarding_probability = "0.75"
    want_forward_retries = "3"