name = "random_walk_test"
[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
build_base_image = "golang:1.23.8-bullseye"
module_path = "github.com/erik9876/go-libp2p-kad-dht/testplans/plans/random_walk_test"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[[testcases]]
name= "random_walk_test"
instances = { min = 5, max = 50, default = 20 }

    [testcases.params]
    want_forwarding_probability = { type = "float", desc = "probability of a want message getting forwarded", default = 0.7 }
