[global]
plan = "dummy_traffic_test"
case = "dummy_traffic_test"
builder = "docker:go"
runner = "local:docker"

[[groups]]
id = "default"
instances.count = 5

    [groups.run]
    [groups.run.test_params]
    dummy_operations_lower_bound = "5"
    dummy_operations_upper_bound = "20"